# Generated by Django 4.1.2 on 2023-01-07 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('announcement', models.TextField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
