# Generated by Django 4.1.2 on 2023-01-07 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('event_date', models.DateField(null=True)),
                ('event_time', models.TimeField(default=datetime.time(0, 0))),
                ('event_headline', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
