# Generated by Django 4.1.2 on 2022-12-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras_names', models.CharField(max_length=35, null=True)),
                ('extras_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_item_name', models.CharField(max_length=35, null=True)),
                ('day_of_the_week', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
