# Generated by Django 4.1.2 on 2022-12-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0002_rename_extras_names_messextras_extras_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmain',
            name='meal_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
