# Generated by Django 4.1.2 on 2022-12-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0003_messmain_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtrasOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('roll_number', models.IntegerField(blank=True)),
                ('order_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
