# Generated by Django 4.1.2 on 2023-01-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0006_rename_meal_type_messmain_type_of_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrasorder',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='extrasorder',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extrasorder',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
