# Generated by Django 4.1.2 on 2023-01-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0007_remove_extrasorder_roll_number_extrasorder_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasorder',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
