# Generated by Django 4.1.2 on 2023-01-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0008_alter_extrasorder_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrasorder',
            name='meal_type',
        ),
    ]
