# Generated by Django 4.1.2 on 2023-01-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0009_remove_extrasorder_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
