# Generated by Django 4.1.2 on 2023-01-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0010_extrasorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrasorder',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='extrasorder',
            name='item_price',
        ),
        migrations.AddField(
            model_name='extrasorder',
            name='item_id',
            field=models.ManyToManyField(to='mess_site.messextras'),
        ),
        migrations.AlterField(
            model_name='extrasorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
