# Generated by Django 4.1.2 on 2023-01-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_site', '0011_remove_extrasorder_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrasorder',
            name='quantity',
        ),
    ]
