# Generated by Django 4.1.2 on 2022-12-25 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_no', models.BigIntegerField(null=True)),
                ('roll_no', models.IntegerField(null=True)),
                ('room_no', models.CharField(max_length=4, null=True)),
                ('hall_no', models.IntegerField(null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_security', models.BooleanField(default=False)),
                ('expense_current', models.IntegerField(default=0)),
                ('expense_last_month', models.IntegerField(default=0)),
                ('expense_total', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(default=0)),
                ('e_0', models.IntegerField(default=0)),
                ('e_1', models.IntegerField(default=0)),
                ('e_2', models.IntegerField(default=0)),
                ('e_3', models.IntegerField(default=0)),
                ('e_4', models.IntegerField(default=0)),
                ('e_5', models.IntegerField(default=0)),
                ('e_6', models.IntegerField(default=0)),
                ('e_7', models.IntegerField(default=0)),
                ('e_8', models.IntegerField(default=0)),
                ('e_9', models.IntegerField(default=0)),
            ],
        ),
    ]
