# Generated by Django 4.1.2 on 2022-12-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
