# Generated by Django 4.1.2 on 2023-01-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_site', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_otp',
            name='user',
        ),
        migrations.AddField(
            model_name='user_otp',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_otp',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
