# Generated by Django 4.1.2 on 2022-12-31 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='date_time',
        ),
        migrations.AddField(
            model_name='query',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
