# Generated by Django 4.1.2 on 2022-12-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResponse',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('response', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
