# Generated by Django 4.1.2 on 2022-12-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresponse',
            name='id_map',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queryresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
