# Generated by Django 4.1.2 on 2023-01-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='QueryResponse',
        ),
    ]
